FROM webbben/pygeoapi-gzip:latest
#pygeoapi last updated 2021-10-15T10:53

#Add data 
COPY ./data /data
COPY ./pygeoapi.config.yml /pygeoapi/local.config.yml
COPY ./schemas.opengis.net /opt/schemas.opengis.net
COPY ./pygeoapi-skin-dashboard /skin-dashboard
