FROM internetofwater/pygeoapi:stable
#pygeoapi last updated 2021-10-30T17:34

#Add data 
COPY ./data /data
COPY ./pygeoapi.config.yml /pygeoapi/local.config.yml
COPY ./schemas.opengis.net /opt/schemas.opengis.net
COPY ./pygeoapi-skin-dashboard /skin-dashboard
